### ISSUE TITLE
0x0b36e80347400447be2483cdc3bce7152bda9e6e : 2 transactions failed

### ISSUE THREAD

**Issue by thedg245** [iExecBlockchainComputing/public-pool-scripts#36]
https://etherscan.io/address/0x0b36e80347400447be2483cdc3bce7152bda9e6e

2 transactions failed

**Comment by vladostp** [comment]
Gas Refund 0.2 ETH - Done
https://etherscan.io/tx/0x9da4661d5b9d341dd185ae0dd7977fb69aa2314aff4f0e7bb5e0d03c8082470b

**Comment by thedg245** [comment]
Thank you for the quick solution.
