### ISSUE TITLE
c96209ea-3586-4b78-8c0f-00721827a46d

### ISSUE THREAD

**Issue by jbdaskie** [iExecBlockchainComputing/public-pool-scripts#37]
Worker ID : c96209ea-3586-4b78-8c0f-00721827a46d (wallet : 0xc582c96B64EE76095AC34F518a6704CC4dA1EcC9)

job reçu traité mais n’apparaît pas - peut être problème passagé ?

**Comment by branciard** [comment]
Your contribution transactions were valid but the work order has an issue as finalizing step : https://explorer.iex.ec/mainnet/work/0x38B5c38C2E35048b36648806995D20021eD08cAC We will manual reward RLC you after the workerdrop.

**Comment by branciard** [comment]
23 RLC manual reward done for 0xc582c96B64EE76095AC34F518a6704CC4dA1EcC9. tx : https://etherscan.io/tx/0xaf6a73d83456f4dcc0ffd19e59daefb660c8a9ec52e4d1a071e3ab1e6e662c3a
