### ISSUE TITLE
0xFF0d9B4B6653E8e18f2A20e46908D7f34C862D4e Had 2 bad transaction((

### ISSUE THREAD

**Issue by ozik1967** [iExecBlockchainComputing/public-pool-scripts#38]
https://etherscan.io/address/0xFF0d9B4B6653E8e18f2A20e46908D7f34C862D4e 
Thanks advance!

**Comment by branciard** [comment]
0.2 ETH has been manually refund : https://etherscan.io/tx/0x0abc75d7cb4d604ae0751b865b15ddd9c335935879c5d48f5ae10fda115134a2


As deposit tx was not successfull ( too long for the client), a contribution with no stake deposit has revert ( try twice). we have remove the deposit constraint in the workorder a few hours ago to prevent others cases like this.

**Comment by ozik1967** [comment]
Thank you so much!!! Very nice job!!!
