### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by tudoranj** [iExecBlockchainComputing/public-pool-scripts#39]
Worker id:017df80d-5beb-4952-930b-befbb274462f 
https://etherscan.io/address/0x09901d6d9c8c4d2c11202cc56202568efbde6fc0
In the information worker, it was shown that one task was completed and one task was in progress. After some time, the result was reset.

**Comment by branciard** [comment]
Your contribution transactions were valid but the work order has an issue as finalizing step : https://explorer.iex.ec/mainnet/work/0x6967b53eC07Bd44cC840b9675CdD27f996bD07e3 We will manual reward RLC to you after the workerdrop.

**Comment by branciard** [comment]
23 RLC manual reward done for worker 0x09901d6d9c8c4d2c11202cc56202568efbde6fc0 see tx : https://etherscan.io/tx/0x5108ad27b7b717efae73f9a5ce0b3377b53c3b3d97771e6563fda1fb050e8a43
