### ISSUE TITLE
Missing task

### ISSUE THREAD

**Issue by Allintether** [iExecBlockchainComputing/public-pool-scripts#46]
Public adress : 0x6462b16f6b15237b4b209f9287adda177bf458b8
https://etherscan.io/address/0x6462b16f6b15237b4b209f9287adda177bf458b8

I only have a score of "2". But i'm pretty sure i had more tasks with WD 2 & 3 (i think i had minimum 1 task during WD2, and 2 tasks during WD3).

I used the same wallet.

Ty.

**Comment by branciard** [comment]
this wallet participate to this workorder completed : 0x43882105ece6dfbcfed1f8377aceab7fbedd59a 

`

iexec work show 0x43882105ece6dfbcfed1f8377aceab7fbedd59a --chain mainnet
ℹ iExec SDK update available 2.2.39 →  2.3.1, Run "npm -g i iexec" to update

ℹ using chain [mainnet]
✔ work 0x43882105ece6dfbcfed1f8377aceab7fbedd59a status is COMPLETED, details:
m_workerpool:          0x0ed5e70874487bf21ee65343fb6c5fa13382cdb6
m_params:              {"cmdline":"monte-carlo normal"}
m_requester:           0x8ec966ff9752c5de46105155ef1e9a3a38542358
m_app:                 0xcb0bba8cf239e167af92a51c4212adbf9b479f6a
m_dataset:             0x0000000000000000000000000000000000000000
m_emitcost:            0
m_uri:                 xw://api-workerdrop-pool.iex.ec/7f1b9b11-d0f1-4e11-bbf7-ffa7e12f0785
m_stdout:
m_resultCallbackProof: 0xe90732a5fe61e16ac5af08c8e2ce69013e488fbd97a00a4b0acdcc13e290aa48
m_iexecHubAddress:     0x0d5ef019ca4c5cc413ee892ced89d7107c5f424d
m_callback:            0x0000000000000000000000000000000000000000
m_status:              4
m_marketorderIdx:      309
m_stderr:
m_beneficiary:         0x0000000000000000000000000000000000000000
m_statusName:          COMPLETED
`

**Score = 0 +1 = 1**

Then this one : 
 iexec work show 0x7ea6629a0913ca8099cf36b89bfdafee41b3f15d --chain mainnet
ℹ iExec SDK update available 2.2.39 →  2.3.1, Run "npm -g i iexec" to update

ℹ using chain [mainnet]
✔ work 0x7ea6629a0913ca8099cf36b89bfdafee41b3f15d status is COMPLETED, details:
m_workerpool:          0x0ed5e70874487bf21ee65343fb6c5fa13382cdb6
m_params:              {"cmdline":"monte-carlo normal"}
m_requester:           0x8ec966ff9752c5de46105155ef1e9a3a38542358
m_app:                 0xcb0bba8cf239e167af92a51c4212adbf9b479f6a
m_dataset:             0x0000000000000000000000000000000000000000
m_emitcost:            0
m_uri:                 xw://api-workerdrop-pool.iex.ec/34dc61c2-608b-48f3-b3eb-b0a15b3eaa2c
m_stdout:
m_resultCallbackProof: 0xc5c2144a338de897b6c2fe6141bbcf57fef2f187d44a86bdde60d9fb508a7b21
m_iexecHubAddress:     0x0d5ef019ca4c5cc413ee892ced89d7107c5f424d
m_callback:            0x0000000000000000000000000000000000000000
m_status:              4
m_marketorderIdx:      365
m_stderr:
m_beneficiary:         0x0000000000000000000000000000000000000000
m_statusName:          COMPLETED


**Score = 1+1 = 2**


Your workorder at WD2 was not completed. => **m_statusName = Claimed**. Score are not updated when order are claimed. So your score is 2. corresponding of the success of the 2 tasks in WD3.

WD2 worker order status in blockchain  : 

```

iexec work show 0x2cb832520fa092010de3bdf8769e059cd0b7f003 --chain mainnet
ℹ iExec SDK update available 2.2.39 →  2.3.1, Run "npm -g i iexec" to update

ℹ using chain [mainnet]
✔ work 0x2cb832520fa092010de3bdf8769e059cd0b7f003 status is CLAIMED, details:
m_workerpool:          0x0ed5e70874487bf21ee65343fb6c5fa13382cdb6
m_params:              {"cmdline":"monte-carlo normal"}
m_requester:           0x8ec966ff9752c5de46105155ef1e9a3a38542358
m_app:                 0xcb0bba8cf239e167af92a51c4212adbf9b479f6a
m_dataset:             0x0000000000000000000000000000000000000000
m_emitcost:            0
m_uri:
m_stdout:
m_resultCallbackProof: 0x0000000000000000000000000000000000000000000000000000000000000000
m_iexecHubAddress:     0x0d5ef019ca4c5cc413ee892ced89d7107c5f424d
m_callback:            0x0000000000000000000000000000000000000000
m_status:              3
m_marketorderIdx:      175
m_stderr:
m_beneficiary:         0x0000000000000000000000000000000000000000
m_statusName:          CLAIMED
```
