### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by a1td** [iExecBlockchainComputing/public-pool-scripts#47]
Hello! Two of my employees got errors during Workerdrop.

0x5a914745Db8D246bd06e1788942fBf84fdd53d56 - could not complete one task and hung on it for many hours, only after rebooting continued to wait for work.
0x326807F595b3c5c77af39E46AA75FDCD8d7643E5 - here is the same error, two tasks failed.

**Comment by branciard** [comment]
I confirm that your contribution was correct on the worker order 0x1af213a78f4a695faa50a0629a8ce12c37b5d79e .
but the work order has an issue as finalizing step.

I will manually reward for this one.

```
 iexec work show 0x1af213a78f4a695faa50a0629a8ce12c37b5d79e --chain mainnet
ℹ iExec SDK update available 2.2.39 →  2.3.1, Run "npm -g i iexec" to update

ℹ using chain [mainnet]
✔ work 0x1af213a78f4a695faa50a0629a8ce12c37b5d79e status is ACTIVE, details:
m_workerpool:          0x0ed5e70874487bf21ee65343fb6c5fa13382cdb6
m_params:              {"cmdline":"monte-carlo normal"}
m_requester:           0x8ec966ff9752c5de46105155ef1e9a3a38542358
m_app:                 0xcb0bba8cf239e167af92a51c4212adbf9b479f6a
m_dataset:             0x0000000000000000000000000000000000000000
m_emitcost:            0
m_uri:
m_stdout:
m_resultCallbackProof: 0x0000000000000000000000000000000000000000000000000000000000000000
m_iexecHubAddress:     0x0d5ef019ca4c5cc413ee892ced89d7107c5f424d
m_callback:            0x0000000000000000000000000000000000000000
m_status:              1
m_marketorderIdx:      351
m_stderr:
m_beneficiary:         0x0000000000000000000000000000000000000000
m_statusName:          ACTIVE

```

same for 0x326807F595b3c5c77af39E46AA75FDCD8d7643E5 . 

2 task to reward manually

**Comment by branciard** [comment]
23 RLC manual reward for worker 0x5a914745Db8D246bd06e1788942fBf84fdd53d56 see tx : https://etherscan.io/tx/0x078a6d6659aaa083b8064f0177d5c19918716ba72be179e2d16723def457f2e6

**Comment by branciard** [comment]
23 *2 = 46 RLC manual reward for worker 0x326807F595b3c5c77af39E46AA75FDCD8d7643E5 see tx  https://etherscan.io/tx/0xe74150d55df0b06fe14351edd58c4c9581d55f260ae1f6ff22e56990d1861487
